### ISSUE TITLE
Error: Offset is out of bounds

### ISSUE THREAD

**Issue by AdamMagaluk** [medea/medea#59]
```
fs.js:533
  binding.read(fd, buffer, offset, length, position, req);
          ^
Error: Offset is out of bounds
    at Error (native)
    at Object.fs.read (fs.js:533:11)
    at Medea.get (/data/run/v0.1.0_1/node_modules/zetta/node_modules/medea/medea.js:537:6)
    at MedeaIterator._next (/data/run/v0.1.0_1/node_modules/zetta/node_modules/medeadown/medeaiterator.js:28:11)
    at AbstractIterator.next (/data/run/v0.1.0_1/node_modules/zetta/node_modules/medeadown/node_modules/abstract-leveldown/abstract-iterator.js:22:17)
    at ReadStream.read [as _read] (/data/run/v0.1.0_1/node_modules/zetta/node_modules/levelup/lib/read-stream.js:81:18)
    at ReadStream.Readable.read (/data/run/v0.1.0_1/node_modules/zetta/node_modules/levelup/node_modules/readable-stream/lib/_stream_readable.js:362:10)
    at ReadStream.<anonymous> (/data/run/v0.1.0_1/node_modules/zetta/node_modules/levelup/node_modules/readable-stream/lib/_stream_readable.js:785:45)
    at ReadStream.emit (events.js:104:17)
    at emitDataEvents (/data/run/v0.1.0_1/node_modules/zetta/node_modules/levelup/node_modules/readable-stream/lib/_stream_readable.js:811:10)
```

**Comment by raleksandar** [comment]
I keep getting this error too, it seems that it has to do something with corrupted entry keys.

To try and debug this issue I have logged entry variable before offending line (medea.js:537) and just before exception is thrown this is logged:

````
{"fileId":10,"valueSize":0,"valuePosition":122,"timestamp":6.780694796723515e-286,"key":"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000vvoFstpYnBekButFBu\r?\u0004´┐¢´┐¢\u0000\u0000\u0010\u0000\u0000\u0000h@Z\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000vvoFstpYnBekButFBu\r?\u0004´┐¢´┐¢\u0000\u0000\u0010\u0000\u0000\u0000h@j\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"}
````

while other entries have normal keys, e.g.:

````
{"fileId":61,"valueSize":366,"valuePosition":34,"timestamp":1446834540943,"key":"0TX7TPtMg9oLhc7Q"}
````

I have no idea how that key represents and what might have corrupted it. The simple solution would be just to add try/catch around that code and ignore corrupted entries which is what I had done (I can live with the fact that some entries can go missing)

**Comment by kevinswiber** [comment]
@raleksandar Have you tried updating to medea@1.0.1?  A PR was merged for that release, and it may fix this problem.

**Comment by raleksandar** [comment]
@kevinswiber You're right, it got fixed in 1.0.1! Thanks!

I haven't realized there was a new release (maybe due to the fact that I don't depend directly on medea, I use it via medeadown package -- I'm gonna check their version strings for medea, they might have it locked at 1.0.0)

**Comment by raleksandar** [comment]
I've just realized that medeadown is not some 3rd-party package and that it's in part of the same GitHub organization as medea :) So it just might be that I haven't run `npm install` in a few days (version string for medea in medeadown package is not a problem) :)

**Comment by kevinswiber** [comment]
Great to hear!  Closing this issue.
